src/Entity/LabApp/Etude.php
<?php

namespace App\Entity\LabApp;

use App\Entity\Fichier;
use App\EtudeResourceInterface;
use App\HasUserBookInterface;
use App\Repository\LabApp\EtudeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EtudeRepository::class)
 */
class Etude implements HasUserBookInterface, EtudeResourceInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $acronyme;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateDebut;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateFin;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resume;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="etude", orphanRemoval=true)
     * @ORM\OrderBy({"date" = "DESC", "id" = "DESC"})
     */
    private $notes;

    /**
     * @ORM\ManyToOne(targetEntity=UserBook::class, inversedBy="etudes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userBook;

    /**
     * @ORM\OneToMany(targetEntity=FichierEtude::class, mappedBy="etude", orphanRemoval=true, cascade={"persist"})
     */
    private $fichierEtudes;

    /**
     * @ORM\OneToOne(targetEntity=Fichier::class, cascade={"persist", "remove"})
     */
    private $banner;

    /**
     * @ORM\ManyToOne(targetEntity=Equipe::class, inversedBy="etudes")
     *
     * @Assert\Valid
     */
    private $equipe;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->notes = new ArrayCollection();
        $this->fichierEtudes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAcronyme(): ?string
    {
        return $this->acronyme;
    }

    public function setAcronyme(string $acronyme): self
    {
        $this->acronyme = $acronyme;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(?\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(?string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setEtude($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getEtude() === $this) {
                $note->setEtude(null);
            }
        }

        return $this;
    }

    public function getStatut(): string
    {
        $now = new \DateTime();

        if (null !== $this->dateDebut && $now < $this->dateDebut) {
            return 'upcoming';
        }

        if (null !== $this->dateFin && $now > $this->dateFin) {
            return 'ended';
        }

        return 'in_progress';
    }

    public function getOwner(): UserBook
    {
        return $this->userBook;
    }

    public function getUserBook(): ?UserBook
    {
        return $this->userBook;
    }

    public function setUserBook(?UserBook $userBook): self
    {
        $this->userBook = $userBook;

        return $this;
    }

    public function getEtude(): Etude
    {
        return $this;
    }

    /**
     * @return Collection|FichierEtude[]
     */
    public function getFichierEtudes(): Collection
    {
        return $this->fichierEtudes;
    }

    public function addFichierEtude(FichierEtude $fichierEtude): self
    {
        if (!$this->fichierEtudes->contains($fichierEtude)) {
            $this->fichierEtudes[] = $fichierEtude;
            $fichierEtude->setEtude($this);
        }

        return $this;
    }

    public function removeFichierEtude(FichierEtude $fichierEtude): self
    {
        if ($this->fichierEtudes->removeElement($fichierEtude)) {
            // set the owning side to null (unless already changed)
            if ($fichierEtude->getEtude() === $this) {
                $fichierEtude->setEtude(null);
            }
        }

        return $this;
    }

    public function getBanner(): ?Fichier
    {
        return $this->banner;
    }

    public function setBanner(?Fichier $banner): self
    {
        $this->banner = $banner;

        return $this;
    }

    public function getEquipe(): ?Equipe
    {
        return $this->equipe;
    }

    public function setEquipe(?Equipe $equipe): self
    {
        $this->equipe = $equipe;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\LabApp\UserBook;
use App\Repository\UserRepository;
use App\Validator as AppAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use libphonenumber\PhoneNumber;
use Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber as AssertPhoneNumber;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Représente un compte RDI-Manager d'un utilisateur.
 *
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 *      fields={"email"},
 *      groups={"Default", "invitation", "registration"},
 *      message="There is already an account with this email"
 * )
 * @UniqueEntity(
 *      fields={"telephone"},
 *      groups={"Default", "invitation", "registration"},
 *      message="There is already an account with this phone number"
 * )
 * @AppAssert\NotBlankEither(fields={"email", "telephone"})
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="json")
     *
     * @Assert\NotBlank
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     *
     * @Assert\NotBlank(groups={"registration"})
     *
     * @Groups({"organigramme","comment"})
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=63, nullable=true)
     *
     * @Assert\NotBlank(groups={"registration"})
     *
     * @Groups({"organigramme","comment"})
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @Assert\Email(mode="strict")
     *
     * @Groups({"organigramme"})
     */
    private $email;

    /**
     * Clé secrète créée lorsque cet user souhaite réinitialiser son mot de passe.
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetPasswordToken;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $resetPasswordTokenExpiresAt;

    /**
     * @ORM\Column(type="phone_number", nullable=true)
     *
     * @AssertPhoneNumber(type="mobile", defaultRegion="FR")
     */
    private $telephone;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * Si cet utilisateur est activé, et peux se connecter à son compte RDI-Manager.
     *
     * @ORM\Column(type="boolean")
     */
    private $enabled;

    /**
     * @ORM\Column(type="boolean")
     */
    private $notificationEnabled;

    /**
     * @ORM\Column(type="boolean")
     */
    private $notificationCreateFaitMarquantEnabled;

    /**
     * @ORM\Column(type="boolean")
     */
    private $notificationLatestFaitMarquantEnabled;

    /**
     * @ORM\Column(type="boolean")
     */
    private $notificationSaisieTempsEnabled;

    /**
     * @ORM\Column(type="boolean", options={"default" : true})
     */
    private $notificationPlanningTaskNotCompletedEnabled;

    /**
     * @ORM\Column(type="boolean", options={"default" : true})
     */
    private $notificationPlanningTaskStartSoonEnabled;

    /**
     * @ORM\Column(type="boolean", options={"default" : true})
     */
    private $notificationEvenementInvitationEnabled;

    /**
     * @ORM\Column(type="boolean")
     */
    private $onboardingEnabled;

    /**
     * @ORM\Column(type="boolean")
     */
    private $onboardingTimesheetCompleted;

    /**
     * Help texts to display, not yet acknowlegded.
     * Null means user not yet logged in, so display all.
     * Empty array means all help texts have been acknowledged.
     *
     * @ORM\Column(type="json", nullable=true)
     */
    private $helpTexts;

    /**
     * All the SocieteUser this user has access to.
     *
     * @ORM\OneToMany(targetEntity=SocieteUser::class, mappedBy="user", cascade={"persist"})
     */
    private $societeUsers;

    /**
     * The current SocieteUser this user has switched to.
     *
     * @ORM\ManyToOne(targetEntity=SocieteUser::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $currentSocieteUser;

    /**
     * @ORM\OneToMany(targetEntity=ProjetObservateurExterne::class, mappedBy="user", orphanRemoval=true)
     */
    private $projetObservateurExternes;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $locale;

    /**
     * @ORM\OneToOne(targetEntity=Fichier::class, cascade={"persist", "remove"})
     *
     * @Groups({"organigramme","comment"})
     */
    private $avatar;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $cguCgvAcceptedAt;

    /**
     * @ORM\OneToMany(targetEntity=DashboardConsolide::class, mappedBy="user", orphanRemoval=true)
     */
    private $dashboardConsolides;

    /**
     * @ORM\OneToMany(targetEntity=BoUserNotification::class, mappedBy="boUser", orphanRemoval=true)
     */
    private $boUserNotifications;

    /**
     * @ORM\OneToMany(targetEntity=UserBook::class, mappedBy="user")
     */
    private $userBooks;

    /**
     * The current UserBook this user has switched to.
     *
     * @ORM\ManyToOne(targetEntity=UserBook::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $currentUserBook;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $patchnoteReaded;

    /**
     * @ORM\OneToMany(targetEntity=Rappel::class, mappedBy="user", orphanRemoval=true)
     */
    private $rappels;

    public function __construct()
    {
        $this->enabled = true;
        $this->roles = ['ROLE_FO_USER'];
        $this->projetParticipants = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->notificationEnabled = true;
        $this->notificationCreateFaitMarquantEnabled = true;
        $this->notificationLatestFaitMarquantEnabled = true;
        $this->notificationSaisieTempsEnabled = true;
        $this->notificationPlanningTaskNotCompletedEnabled = true;
        $this->notificationPlanningTaskStartSoonEnabled = true;
        $this->notificationEvenementInvitationEnabled = true;
        $this->onboardingEnabled = true;
        $this->onboardingTimesheetCompleted = false;
        $this->societeUsers = new ArrayCollection();
        $this->projetObservateurExternes = new ArrayCollection();
        $this->locale = 'fr';
        $this->patchnoteReaded = false;
        $this->dashboardConsolides = new ArrayCollection();
        $this->boUserNotifications = new ArrayCollection();
        $this->userBooks = new ArrayCollection();
        $this->rappels = new ArrayCollection();
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return $this->email ?? $this->telephone->getNationalNumber();
    }

    public function getResetPasswordToken(): ?string
    {
        return $this->resetPasswordToken;
    }

    public function setResetPasswordToken(?string $resetPasswordToken): self
    {
        $this->resetPasswordToken = $resetPasswordToken;

        return $this;
    }

    public function hasResetPasswordToken(): bool
    {
        return null !== $this->resetPasswordToken
            && new \DateTime() < $this->resetPasswordTokenExpiresAt
        ;
    }

    public function removeResetPasswordToken(): self
    {
        $this->resetPasswordToken = null;
        $this->resetPasswordTokenExpiresAt = null;

        return $this;
    }

    public function getResetPasswordTokenExpiresAt(): ?\DateTime
    {
        return $this->resetPasswordTokenExpiresAt;
    }

    public function setResetPasswordTokenExpiresAt(?\DateTime $resetPasswordTokenExpiresAt): self
    {
        $this->resetPasswordTokenExpiresAt = $resetPasswordTokenExpiresAt;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function setRole(string $role): self
    {
        $this->roles = [$role];

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getFullname(): string
    {
        if (null === $this->prenom && null === $this->nom) {
            return '-';

src/Controller/LabApp/CommingSoonController.php
<?php

namespace App\Controller\LabApp;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CommingSoonController extends AbstractController
{
    /**
     * @Route("/comming-soon", name="lab_app_comming_soon")
     */
    public function index(): Response
    {
        if (str_contains($this->getParameter('router.request_context.host'), 'afpa')){
            return $this->redirectToRoute('lab_app_fo_multi_user_book_switch');
        }
        return $this->render('_comming_soon.html.twig');
    }
}

src/Controller/LabApp/FO/Admin/EquipeController.php
<?php

namespace App\Controller\LabApp\FO\Admin;

use App\MultiSociete\UserContext;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/equipes")
 */
class EquipeController extends AbstractController
{
    /**
     * @Route("/liste", name="lab_app_fo_admin_equipes")
     *
     * @ParamConverter("labo", options={"id" = "laboId"})
     */
    public function list(UserContext $userContext)
    {
        $labo = $userContext->getUserBook()->getLabo();

        $equipes = $labo->getEquipes();

        return $this->render('lab_app/equipe/admin_list.html.twig', [
            'equipes'=> $equipes,
        ]);
    }
}

templates/lab_app/etude/edit_banner.html.twig
{% extends 'lab_app/base.html.twig' %}

{% block title %}{{ 'etude.banner'|trans }} | {{ parent() }}{% endblock %}

{% block body %}

<h1>{{ 'etude.banner'|trans }}</h1>


<div class="row">
    <div class="col-md-6 offset-md-3">

        <a class="d-block mb-4" href="{{ path('lab_app_fo_etude', {id: etude.id}) }}">
            <i class="fa fa-chevron-left" aria-hidden="true"></i>
            {{ "return_to_etude"|trans }}
        </a>

        {% if etude.banner and etude.banner %}
        <p>{{ 'etude.current_banner'|trans }} :</p>

        <div class="img-uploaded-container">
            <img src="{{ etude|bannerUrl }}" class="mb-4"/>
        </div>
        {% endif %}

        <p>{{ 'etude.new_banner'|trans }} :</p>

        {{ form_start(form) }}
        {{ form_errors(form) }}

        {{ form_row(form.file) }}

        <button type="submit" class="btn btn-success">{{ 'update'|trans }}</button>

        {{ form_end(form) }}
    </div>
</div>

{% endblock %}

templates/lab_app/etude/fiche_etude-main.html.twig
<div class="card bg-light-grey border-light">
    <div class="card-body">

        <h2 class="text-center mt-0 mb-4">{{ etude.title }} ({{ etude.acronyme }})</h2>

        <div class="text-justify">
            <p class="m-0">{{ etude.resume|markdown|raw }}</p>
        </div>
    </div>
</div>

<div class="card border-light d-md-none">
    <div class="card-body">
        {% include 'lab_app/etude/fiche_etude-sidebar.html.twig' %}
    </div>
</div>

<section id="timeline">
    <h2 class="facts">Notes</h2>

    <ul class="timeline">
        <div class="add-etude">
            {% if userCanAddNote %}
                <a
                        href="{{ path('lab_app_fo_note_ajouter', { 'etudeId' : etude.id }) }}"
                        class="btn btn-lg btn-outline-primary"
                >
                    <i class="fa fa-plus" aria-hidden="true"></i>
                    <span class="d-xs-none d-sm-none d-md-none d-xl-inline-block d-lg-inline-block">{{ 'add_new_note'|trans }}</span>
                </a>
            {% else %}
                <p class="text-muted text-left">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                    {{ "note.create_only_by_owner"|trans }}
                </p>
            {% endif %}
        </div>
        <table id="etude_timeline_dt" class="table datatable custom-datatable text-word-break">
            <thead><tr><th>Notes</th></tr></thead>
            <tbody>
            {% for note in etude.notes %}
                <tr>
                    <td>
                        <li class="event" id="note-{{ note.id }}">
                            <h4 class="d-flex flex-row justify-content-between align-items-center" data-date="{{ note.date|format_date }}">
                                <span>
                                    {{ note.date|format_date }}
                                    -
                                    <a
                                            href="#"
                                    >
                                        {% include 'utils/_avatar.html.twig' with {user: note.createdBy.user, size: 24, toExpend: true} %}
                                        {{ note.createdBy.user.fullname }}
                                    </a>
                                </span>
                                <div>
                                    <a
                                            href="{{ path('lab_app_fo_note_modifier', {'id' : note.id}) }}" style="font-size: 1.2rem;"
                                            class="edit-note {% if not is_granted(constant('App\\EtudeResourceInterface::EDIT'), note) %}disabled{% endif %}"
                                            {% if not is_granted(constant('App\\EtudeResourceInterface::EDIT'), note) %}
                                                disabled
                                                title="Vous ne pouvez pas modifier les notes qui ne vous appartiennent pas"
                                            {% else %}
                                                title="{{ "edit_btn"|trans }}"
                                            {% endif %}
                                    >
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                </div>

                            </h4>
                            <h3>{{ note.title }}</h3>
                            {% if note.isReadingNote %}
                            <div class="note-reading-content">
                                <p><strong>{{ 'note.readingName'|trans }} : </strong> {{ note.readingName }}</p>
                                <p><strong>{{ 'note.author'|trans }} : </strong> {{ note.author }}</p>
                                <p><strong>{{ 'note.reference'|trans }} : </strong> {{ note.reference }}</p>
                            </div>
                            {% endif %}
                            <div class="note-content event-content text-justify text-word-break position-relative overflow-hidden">
                                {{ note.description|markdown|raw }}
                            </div>
                            <ul class="list-unstyled mt-3">
                                {% for fichierEtude in note.fichierEtudes %}
                                    <li>
                                        <i class="fa {{ fichierEtude.fichier|faFileIcon }}" aria-hidden="true"></i>
                                        <a target="_blank"
                                           href="{{ path('lab_app_fo_etude_fichier', {
                                               'etudeId': etude.id,
                                               'fichierEtudeId': fichierEtude.id
                                           }) }}" {% if fichierEtude.fichier|isImageFile %} miniature {% else %} title="{{ 'download'|trans }}" {% endif %}>
                                            {{ fichierEtude.fichier.nomFichier }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </ul>
</section>

templates/lab_app/etude/fiche_etude-sidebar.html.twig
<dl>
    {% if etude.userBook.labo is not null %}
        <dt><i class="fa fa-flask"></i> {{ "labo.string"|trans }}</dt>
        <dd>{{ etude.userBook.labo.name }}</dd>
    {% endif %}
    {% if etude.dateDebut %}
        <dt><i class="fa fa-calendar"></i> {{ "etude.dateDebut"|trans }}</dt>
        <dd>{{ etude.dateDebut|format_date }}</dd>
    {% endif %}
    {% if etude.dateFin %}
        <dt><i class="fa fa-calendar"></i> {{ "etude.dateFin"|trans }}</dt>
        <dd>{{ etude.dateFin|format_date }}</dd>
    {% endif %}
    <dt><i class="fa fa-bar-chart"></i> {{ "etude.status"|trans }}</dt>
    <dd>{{ etude.statut | trans }}</dd>
</dl>

<hr>

<a
        href="{{ path('lab_app_fo_etude_fichiers', {'id': etude.id}) }}"
        class="btn btn-outline-primary rounded-circle float-right {{ userCanAddNote ? '' : 'disabled' }}"
        {% if not userCanAddNote %}
            title="Seul le propriétaire est autorisé à ajouter un fichier"
        {% else %}
            title="Ajouter un fichier"
        {% endif %}
><i class="fa fa-upload" aria-hidden="true"></i>
</a>

<h4>{{ "filesString"|trans }}</h4>

{% if etude.fichierEtudes|length > 0 %}

    <ul class="list-unstyled">
        {% for fichierEtude in etude.fichierEtudes|reverse[0:5] %}
            <li>
                <a href="{{ path('lab_app_fo_etude_fichier', {'etudeId': etude.id, 'fichierEtudeId': fichierEtude.id}) }}" target="_blank"
                        {% if fichierEtude.fichier|isImageFile %} miniature {% else %} title="{{ 'download'|trans }}" {% endif %}>
                    <i class="fa {{ fichierEtude.fichier|faFileIcon }}" aria-hidden="true"></i>
                    {{ fichierEtude.fichier.nomFichier }}
                </a>
            </li>
        {% endfor %}
    </ul>

    {% if etude.fichierEtudes|length > 5 %}
        <p>{{ '...and_n_others' | trans({'n': etude.fichierEtudes|length - 5}) }}</p>
    {% endif %}

    <a href="{{ path('lab_app_fo_etude_fichiers', {'id': etude.id}) }}">{{ "list_files"|trans }}</a>

{% else %}

    <p class="text-muted">
        <small>
            {{ "no_files_here"|trans }}
        </small>
    </p>

{% endif %}

templates/lab_app/etude/fiche_etude.html.twig
{% extends "lab_app/base.html.twig" %}

{% block title %}{{ 'etude.string'|trans }} {{ etude.acronyme }} | {{ parent() }}{% endblock %}

{% block body %}

<div class="row">
    <div class="col-12 col-md-8 etude-banner">
        <div class="etude-banner-background" style="background-image: url({{ etude|bannerUrl }})"></div>

        <div class="etude-banner-text">
            <p class="text-center m-0">
                {% include 'utils/_avatar.html.twig' with {user: etude.owner.user, size: 28, toExpend: true} %}
                {{ etude.owner.user.fullnameOrEmail }}
            </p>
        </div>

        <div class="btn-edit-banner">
            <a
                    href="{{ path('lab_app_fo_etude_banner_modifier', {'id': etude.id}) }}"
                    class="btn btn-sm btn-secondary rounded-circle {{ userCanEditEtude ? '' : 'disabled' }}"
                    title="Modifier la bannière {{ userCanEditEtude ? '' : '(Pas d\'accès)' }}"
            ><i class="fa fa-pencil"></i></a>
        </div>
    </div>
    <div class="col-12 col-md-4">
        <div class="projet-actions">
            <a
                href="{{ path('lab_app_fo_etude_modifier', {'id': etude.id}) }}"
                class="btn btn-outline-primary rounded-circle {{ userCanEditEtude ? '' : 'disabled' }}"
                title="Paramétrage de l'étude {{ userCanEditEtude ? '' : '(Pas d\'accès)' }}"
            ><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12 col-md-8">
        {% include 'lab_app/etude/fiche_etude-main.html.twig' %}
    </div>
    <aside class="col-12 col-md-4 d-none d-md-block">
        {% include 'lab_app/etude/fiche_etude-sidebar.html.twig' %}
    </aside>
</div>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('fiche-etude') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('fiche-etude') }}
{% endblock %}

templates/lab_app/etude/list.html.twig
{% extends 'lab_app/base.html.twig' %}

{% block title %}{{ 'menu.etude.list'|trans }} | {{ parent() }}{% endblock %}

{% block body %}

    <h1>{{ 'menu.etude.list'|trans }}</h1>

    <div class="my-3 text-right">
        <a href="{{ path('lab_app_fo_etude_creation') }}" class="btn btn-outline-primary">
            <i class="fa fa-plus-square" aria-hidden="true"></i> {{ 'menu.etude.create'|trans }}
        </a>
    </div>

    <table class="table datatable hover" data-order='[[ 0, "asc" ]]'>
        <thead>
            <tr>
                <th>{{ 'etude.acronyme'|trans }}</th>
                <th>{{ 'etude.title'|trans }}</th>
                <th>{{ 'etude.dateDebut'|trans }}</th>
                <th>{{ 'etude.dateFin'|trans }}</th>
                <th>{{ 'etude.status'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            {% for etude in etudes %}
                <tr>
                    <td class="text-left"><a href="{{ path('lab_app_fo_etude', { 'id' : etude.id }) }}">{{ etude.acronyme }}</a></td>
                    <td class="text-left">{{ etude.title }}</td>
                    <td class="text-center" data-sort='{{ etude.dateDebut ? etude.dateDebut|date('Ymd') : '' }}'>{{ etude.dateDebut ? etude.dateDebut|date('d/m/Y') : '-' }}</td>
                    <td class="text-center" data-sort='{{ etude.dateFin ? etude.dateFin|date('Ymd') : '' }}'>{{ etude.dateFin ? etude.dateFin|date('d/m/Y') : '-' }}</td>
                    <td class="text-center">{{ etude.statut | trans }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}