src/Entity/Cra.php
<?php

namespace App\Entity;

use App\HasSocieteInterface;
use App\Repository\CraRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Détermine quels jours un utilisateur a travaillé sur un mois donné.
 *
 * @ORM\Entity(repositoryClass=CraRepository::class)
 * @UniqueEntity(
 *     fields={"societeUser", "mois"},
 *     errorPath="mois",
 *     message="Cet utilisateur a déjà soumis un CRA sur ce mois. Il faut modifier l'autre CRA plutôt."
 * )
 */
class Cra implements HasSocieteInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=SocieteUser::class, inversedBy="cras")
     * @ORM\JoinColumn(nullable=false)
     */
    private $societeUser;

    /**
     * @ORM\Column(type="date")
     */
    private $mois;

    /**
     * Tableau contenant une liste de '1', '0' ou '0.5'
     * correspondant aux jours travaillés dans le mois.
     *
     * @ORM\Column(type="simple_array", nullable=true)
     *
     * @var float[]
     */
    private $jours = [];

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $craModifiedAt;

    /**
     * @ORM\Column(type="date", nullable=true)
     *
     * @Serializer\Groups({"Default", "saisieTemps"})
     */
    private $tempsPassesModifiedAt;

    /**
     * @ORM\OneToMany(targetEntity=TempsPasse::class, mappedBy="cra", orphanRemoval=true, cascade={"persist"})
     *
     * @Serializer\Groups({"Default", "saisieTemps"})
     */
    private $tempsPasses;

    public function __construct()
    {
        $this->tempsPasses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSocieteUser(): ?SocieteUser
    {
        return $this->societeUser;
    }

    public function setSocieteUser(?SocieteUser $societeUser): self
    {
        $this->societeUser = $societeUser;

        return $this;
    }

    public function getMois(): ?\DateTimeInterface
    {
        return $this->mois;
    }

    public function setMois(\DateTimeInterface $mois): self
    {
        $this->mois = $mois;

        return $this;
    }

    /**
     * @return float[]
     */
    public function getJours(): ?array
    {
        return array_map('floatval', $this->jours);
    }

    /**
     * @param float[] $jours
     *
     * @return self
     */
    public function setJours(?array $jours): self
    {
        $this->jours = $jours;

        return $this;
    }

    public function getCraModifiedAt(): ?\DateTimeInterface
    {
        return $this->craModifiedAt;
    }

    public function setCraModifiedAt(?\DateTimeInterface $craModifiedAt): self
    {
        $this->craModifiedAt = $craModifiedAt;

        return $this;
    }

    public function getTempsPassesModifiedAt(): ?\DateTimeInterface
    {
        return $this->tempsPassesModifiedAt;
    }

    public function setTempsPassesModifiedAt(?\DateTimeInterface $tempsPassesModifiedAt): self
    {
        $this->tempsPassesModifiedAt = $tempsPassesModifiedAt;

        return $this;
    }

    /**
     * @return Collection|TempsPasse[]
     */
    public function getTempsPasses(): Collection
    {
        return $this->tempsPasses;
    }

    public function hasTempsPasses(): bool
    {
        return count($this->tempsPasses) > 0;
    }

    public function addTempsPass(TempsPasse $tempsPasse): self
    {
        if (!$this->tempsPasses->contains($tempsPasse)) {
            $this->tempsPasses[] = $tempsPasse;
            $tempsPasse->setCra($this);
        }

        return $this;
    }

    public function removeTempsPass(TempsPasse $tempsPasse): self
    {
        if ($this->tempsPasses->contains($tempsPasse)) {
            $this->tempsPasses->removeElement($tempsPasse);
            // set the owning side to null (unless already changed)
            if ($tempsPasse->getCra() === $this) {
                $tempsPasse->setCra(null);
            }
        }

        return $this;
    }

    public function isCraSubmitted(): bool
    {
        if (null === $this->id) {
            return false;
        }

        return null !== $this->craModifiedAt;
    }

    public function isTempsPassesSubmitted(): bool
    {
        foreach ($this->tempsPasses as $tempsPasse) {
            if (null === $tempsPasse->getId()) {
                return false;
            }
        }

        return null !== $this->tempsPassesModifiedAt;
    }

    public function getSociete(): ?Societe
    {
        return $this->societeUser->getSociete();
    }

    /**
     * Vérifie qu'une liste de pourcentage de temps passés est valide.
     *
     * @Assert\Callback
     *
     * @param TempsPasse[] $tempsPasses
     */
    public function checkPercents(ExecutionContextInterface $context, $payload)
    {
        $maxDays = 1;

        // Check every single percent is between 0 and 100
        foreach ($this->tempsPasses as $tempsPasse) {
            foreach ($tempsPasse->getPourcentages() as $percent) {
                if ($percent < 0 || $percent > 100) {
                    $context
                        ->buildViolation(sprintf(
                            'Un pourcentage doit être entre 0 et 100, %d obtenu.',
                            $percent
                        ))
                        ->addViolation()
                    ;

                    break;
                }
            }

            $maxDays = max($maxDays, count($tempsPasse->getPourcentages()));
        }

        // Check total percents of every days are <= 100
        for ($i = 0; $i < $maxDays; ++$i) {
            $total = 0;

            foreach ($this->tempsPasses as $tempsPasse) {
                $total += $tempsPasse->getPourcentage($i);
            }

            if ($total > 100) {
                $context
                    ->buildViolation(sprintf(
                        'La somme des pourcentages doit être entre 0 et 100, %d obtenu.',
                        $total
                    ))
                    ->addViolation()
                ;

                break;
            }
        }
    }
}

src/Controller/CorpApp/FO/Admin/TimesheetController.php
<?php

namespace App\Controller\CorpApp\FO\Admin;

use App\DTO\FilterTimesheet;
use App\Form\FilterTimesheetType;
use App\Repository\SocieteUserRepository;
use App\Service\Timesheet\Event\TimesheetEvent;
use App\Service\Timesheet\Export\TimesheetExporter;
use App\Service\Timesheet\TimesheetCalculator;
use App\MultiSociete\UserContext;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;

class TimesheetController extends AbstractController
{
    /**
     * @Route(
     *      "/feuille-de-temps/generer",
     *      name="corp_app_fo_admin_timesheet_generate"
     * )
     */
    public function generate(
        Request $request,
        TimesheetCalculator $timesheetCalculator,
        TimesheetExporter $timesheetExporter,
        EventDispatcherInterface $dispatcher,
        UserContext $userContext,
        SocieteUserRepository $societeUserRepository
    ) {
        $societeUsers = $societeUserRepository->findBySameSociete($userContext->getSocieteUser());
        $filter = new FilterTimesheet();
        $filter
            ->setUsers($societeUsers)
            ->setFrom((new DateTime())->modify('-1 month'))
        ;
        $form = $this->createForm(FilterTimesheetType::class, $filter);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $timesheets = $timesheetCalculator->generateMultipleTimesheets($filter);

            $dispatcher->dispatch(new TimesheetEvent($userContext->getSocieteUser()), TimesheetEvent::GENERATED);

            return $timesheetExporter->export($timesheets, $filter->getFormat());
        }

        return $this->render('corp_app/timesheet/generate.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/CorpApp/FO/Equipe/TimesheetController.php
<?php

namespace App\Controller\CorpApp\FO\Equipe;

use App\DTO\FilterTimesheet;
use App\Form\FilterTimesheetType;
use App\Repository\SocieteUserRepository;
use App\Service\Timesheet\Event\TimesheetEvent;
use App\Service\Timesheet\Export\TimesheetExporter;
use App\Service\Timesheet\TimesheetCalculator;
use App\MultiSociete\UserContext;
use App\SocieteProduct\Product\ProductPrivileges;
use App\SocieteProduct\Voter\HasProductPrivilegeVoter;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;

class TimesheetController extends AbstractController
{
    /**
     * @Route(
     *      "/feuille-de-temps/generer",
     *      name="corp_app_fo_mon_equipe_timesheet_generate"
     * )
     */
    public function generate(
        Request $request,
        TimesheetCalculator $timesheetCalculator,
        TimesheetExporter $timesheetExporter,
        EventDispatcherInterface $dispatcher,
        UserContext $userContext,
        SocieteUserRepository $societeUserRepository
    ) {
        $this->denyAccessUnlessGranted(HasProductPrivilegeVoter::NAME, ProductPrivileges::SOCIETE_HIERARCHICAL_SUPERIOR);

        $societeUsers = $societeUserRepository->findTeamMembers($userContext->getSocieteUser());

        $filter = new FilterTimesheet();
        $filter
            ->setUsers($societeUsers)
            ->setFrom((new DateTime())->modify('-1 month'))
        ;
        $form = $this->createForm(FilterTimesheetType::class, $filter,[
            'forTeamMembers' => true
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $timesheets = $timesheetCalculator->generateMultipleTimesheets($filter);

            $dispatcher->dispatch(new TimesheetEvent($userContext->getSocieteUser()), TimesheetEvent::GENERATED);

            return $timesheetExporter->export($timesheets, $filter->getFormat());
        }

        return $this->render('corp_app/timesheet/generate.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/corp_app/timesheet/pdf/_sheet.html.twig
<h1>Feuille de temps</h1>

<div class="row">
    <div class="col-6">
        <dl class="row">
            <dt class="col-3">{{ 'lastname'|trans }}</dt>
            <dd class="col-9">{{ timesheet.cra.societeUser.user.nom }}</dd>

            <dt class="col-3">{{ 'firstname'|trans }}</dt>
            <dd class="col-9">{{ timesheet.cra.societeUser.user.prenom }}</dd>

            <dt class="col-3">{{ 'email'|trans }}</dt>
            <dd class="col-9">{{ timesheet.cra.societeUser.user.email }}</dd>
        </dl>
    </div>
    <div class="col-6">
        <dl class="row">
            <dt class="col-3">{{ 'company'|trans }}</dt>
            <dd class="col-9">{{ timesheet.cra.societeUser.societe.raisonSociale }}</dd>

            <dt class="col-3">{{ 'worked_hours_per_day'|trans }}</dt>
            <dd class="col-9">{{ timesheet.heuresParJours|round(2) }} h</dd>
        </dl>
    </div>
</div>

<h2>{{ timesheet.cra.mois|format_date(pattern='MMMM yyyy')|capitalize }}</h2>

<table class="table table-sm table-bordered text-center">
    <thead>
        <tr>
            <th></th>

            {% for key, jour in timesheet.cra.jours %}
                <th class="rdi-cra-col">
                    {{ timesheet.cra.mois|date_modify('+'~key~' day')|format_date(pattern='ccccc d')|upper|replace({' ': '\n'})|nl2br }}
                </th>
            {% endfor %}

            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for projet in timesheet.projets %}
            <tr>
                {# Projet #}
                <th>
                    {{ projet.participation.projet.acronyme }}
                    <br>
                    <small class="text-muted">{{ projet.participation.role|trans }}</small>
                </th>

                {# Détails par jour #}
                {% for key, jour in timesheet.cra.jours %}
                    {% if projet.hasValue %}
                        <td class="rdi-cra-value">{{ projet.workedHours[key]|round(2) }}</td>
                    {% else %}
                        <td class="rdi-cra-value">-</td>
                    {% endif %}
                {% endfor %}

                {# Total heures #}
                <td>
                    <strong>{{ 'n_hours_short'|trans({'%n%': projet.totalWorkedHours|round(2)}) }}</strong>
                </td>
            </tr>
        {% endfor %}

        {# Présence #}
        <tr>
            <th>
                {{ 'presence'|trans }}
                <br>
                <small class="text-muted">
                    {{ '.in_days_unit'|trans }}
                </small>
            </th>
            {% for jour in timesheet.cra.jours %}
                <td class="rdi-cra-value"><strong>{{ jour }}</strong></td>
            {% endfor %}

            <td><strong>{{ 'n_days_short'|trans({'%n%': timesheet.totalJours}) }}</strong></td>
        </tr>
    </tbody>
</table>

<p class="text-right lead">
    {{ 'total_hours_in_month:'|trans({'%month%': timesheet.cra.mois|format_date(pattern='MMMM yyyy')}) }}
    <strong>{{ 'n_hours_short'|trans({'%n%': timesheet.totalWorkedHours|round(2)}) }}</strong>
</p>
<p class="text-right text-muted">
    {{ '.or_n_percent'|trans({'%n%': timesheet.totalPourcentage}) }}
</p>

templates/corp_app/timesheet/pdf/pdf.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <title>Feuille de temps | RDI-Manager</title>

        {% for file in encore_entry_css_files('timesheet-pdf') %}
            <link href="{{ absolute_url(asset(file)) }}" rel="stylesheet" />
        {% endfor %}
    </head>
    <body>
        {% if timesheets is not defined %}
            {% set timesheets = [timesheet] %}
        {% endif %}

        {% for timesheet in timesheets %}
            <section class="pdf-page">
                {% include 'corp_app/timesheet/pdf/_sheet.html.twig' with {
                    'timesheet': timesheet
                } %}
            </section>
        {% endfor %}
    </body>
</html>