src/Entity/Societe.php
<?php

namespace App\Entity;

use App\HasSocieteInterface;
use App\Repository\SocieteRepository;
use App\SocieteProduct\Product\StarterProduct;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Validator\Constraints as Assert;
use App\DTO\ListCurrencies;

/**
 * @ORM\Entity(repositoryClass=SocieteRepository::class)
 */
class Societe implements HasSocieteInterface
{
    /**
     * Nombre d'heures par jours défini par défaut
     * lorsque une société est créée.
     *
     * @param float
     */
    public const DEFAULT_HEURES_PAR_JOURS = 7;

    /**
     * Heure de début du travail définie par défaut
     * lorsque une société est créée.
     *
     * @param float
     */
    public const DEFAULT_WORK_START_TIME = "09:00";

    /**
     * Heure de fin du travail définie par défaut
     * lorsque une société est créée.
     *
     * @param float
     */
    public const DEFAULT_WORK_END_TIME = "17:00";

    /**
     * This societe has been created by someone who followed
     * the inscription tunnel (/creer-ma-societe).
     *
     * @param string
     */
    public const CREATED_FROM_INSCRIPTION = 'INSCRIPTION';

    /**
     * This societe has been created by a back office user.
     *
     * @param string
     */
    public const CREATED_FROM_BACK_OFFICE = 'BACK_OFFICE';

    /**
     * This societe has been created from command line, with "app:init-societe-referent".
     *
     * @param string
     */
    public const CREATED_FROM_COMMAND = 'COMMAND';

    /**
     * User fill their timesheet once a month.
     *
     * @param string
     */
    public const GRANULARITY_MONTHLY = 'monthly';

    /**
     * User fill their timesheet once a week.
     *
     * @param string
     */
    public const GRANULARITY_WEEKLY = 'weekly';

    /**
     * User fill their timesheet every day.
     *
     * @param string
     */
    public const GRANULARITY_DAILY = 'daily';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="uuid", unique=true)
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $raisonSociale;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $siret;

    /**
     * Heures travaillées par jours par défaut par les employés.
     *
     * @ORM\Column(type="decimal", precision=5, scale=3, nullable=true)
     */
    private $heuresParJours;

    /**
     * @ORM\Column(type="string", length=5, nullable=true, options={"default" : self::DEFAULT_WORK_START_TIME})
     *
     * @Assert\Regex(
     *     pattern="/^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$/",
     *     match= true,
     *     message="Work start time is invalid"
     *     )
     */
    private $workStartTime;

    /**
     * @ORM\Column(type="string", length=5, nullable=true, options={"default" : self::DEFAULT_WORK_END_TIME})
     *
     * @Assert\Regex(
     *     pattern="/^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$/",
     *     match= true,
     *     message="Work end time is invalid"
     *     )
     */
    private $workEndTime;

    /**
     * Coût moyen d'1 ETP R&D
     *
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $coutEtp;

    /**
     * @ORM\OneToMany(targetEntity=SocieteUser::class, mappedBy="societe", orphanRemoval=true, cascade={"persist"})
     *
     * @Assert\Valid(groups={"Default", "invitation"})
     */
    private $societeUsers;

    /**
     * Utilise ou non les SMS pour les notifications importantes.
     *
     * @ORM\Column(type="boolean")
     */
    private $smsEnabled;

    /**
     * @ORM\OneToMany(targetEntity=SlackAccessToken::class, mappedBy="societe")
     */
    private $slackAccessTokens;

    /**
     * @ORM\OneToMany(targetEntity=Projet::class, mappedBy="societe")
     */
    private $projets;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * How this Societe has been created (back office, inscription, ...)
     *
     * @ORM\Column(type="string", length=31, nullable=true)
     */
    private $createdFrom;

    /**
     * Who created this Societe (admin, back office user, ...)
     *
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $createdBy;

    /**
     * One of self::GRANULARITY_*
     *
     * @ORM\Column(type="string", length=31)
     */
    private $timesheetGranularity;

    /**
     * Limit character of description field of Fait Marquant
     *
     * @ORM\Column(type="integer", options={"default" : 751})
     */
    private $faitMarquantMaxDesc;

    /**
     * Limit character is blocking or not
     * @ORM\Column(type="boolean", options={"default" : true})
     */
    private $faitMarquantMaxDescIsblocking;

    /**
     * @ORM\OneToOne(targetEntity=Fichier::class, cascade={"persist", "remove"})
     */
    private $logo;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $usedProjectColors = [];

    /**
     * @ORM\Column(type="string", length=10, options={"default" : "#ce352c"})
     */
    private $colorCode;

    /**
     * @ORM\Column(type="string", length=255, options={"default" : "STARTER"})
     */
    private $productKey;

    /**
     * Time to wait before sending another onboarding notification.
     *
     * @ORM\Column(type="string", length=255, options={"default" : "2 weeks"})
     */
    private $onboardingNotificationEvery;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default" : ListCurrencies::DEFAULT_CURRENCY})
     */
    private $currency;

    /**
     * @ORM\Column(type="boolean", options={"default" : true})
     */
    private $enabled;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $onStandBy;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $disabledAt;

    public function __construct()
    {
        $this->enabled = true;
        $this->onStandBy = false;
        $this->uuid = Uuid::uuid4();
        $this->societeUsers = new ArrayCollection();
        $this->heuresParJours = self::DEFAULT_HEURES_PAR_JOURS;
        $this->workStartTime = self::DEFAULT_WORK_START_TIME;
        $this->workEndTime = self::DEFAULT_WORK_END_TIME;
        $this->smsEnabled = true;
        $this->slackAccessTokens = new ArrayCollection();
        $this->projets = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->timesheetGranularity = self::GRANULARITY_MONTHLY;
        $this->faitMarquantMaxDesc = 751;
        $this->faitMarquantMaxDescIsblocking = true;
        $this->colorCode = '#ce352c';
        $this->productKey = StarterProduct::PRODUCT_KEY;
        $this->onboardingNotificationEvery = '2 weeks';
        $this->currency = ListCurrencies::DEFAULT_CURRENCY;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): UuidInterface
    {
        return $this->uuid;
    }

    public function setUuid(UuidInterface $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): self
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getHeuresParJours(): ?float
    {
        return $this->heuresParJours;
    }

    public function setHeuresParJours(?float $heuresParJours): self
    {
        $this->heuresParJours = $heuresParJours;

        return $this;
    }

    /**
     * @return Collection|SocieteUser[]
     */
    public function getSocieteUsers(): Collection
    {
        return $this->societeUsers;
    }

    /**
     * @return Collection|SocieteUser[]
     */
    public function getEnableSocieteUsers(): Collection
    {
        return $this->societeUsers->filter(function (SocieteUser $societeUser) {
            return $societeUser->getEnabled();
        });
    }

    /**
     * @return Collection|SocieteUser[]
     */
    public function getDisableSocieteUsers(): Collection
    {
        return $this->societeUsers->filter(function (SocieteUser $societeUser) {
            return !$societeUser->getEnabled();
        });
    }

    /**
     * @return Collection|SocieteUser[]
     */
    public function getActiveSocieteUsers(): Collection
    {
        return $this->societeUsers->filter(function (SocieteUser $societeUser) {
            return $societeUser->hasUser() && $societeUser->getEnabled();
        });
    }

    public function addSocieteUser(SocieteUser $user): self
    {
        if (!$this->societeUsers->contains($user)) {
            $this->societeUsers[] = $user;
            $user->setSociete($this);
        }

        return $this;
    }

    public function removeSocieteUser(SocieteUser $user): self
    {
        if ($this->societeUsers->contains($user)) {
            $this->societeUsers->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getSociete() === $this) {
                $user->setSociete(null);
            }
        }

        return $this;
    }

    public function getAdmins(): ArrayCollection
    {
        return $this->societeUsers->filter(function (SocieteUser $societeUser) {
            return $societeUser->isAdminFo();
        });
    }

    public function getSmsEnabled(): ?bool
    {
        return $this->smsEnabled;
    }

    public function setSmsEnabled(bool $smsEnabled): self
    {
        $this->smsEnabled = $smsEnabled;

src/LicenseGeneration/Form/SocieteType.php
<?php

namespace App\LicenseGeneration\Form;

use App\Entity\Societe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SocieteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('uuid', null, [
                'disabled' => true,
            ])
            ->add('raisonSociale', null, [
                'disabled' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Societe::class,
        ]);
    }
}

src/Controller/BO/API/BoUserNotificationController.php
<?php

namespace App\Controller\BO\API;

use App\Entity\SocieteUser;
use App\Entity\User;
use App\Listener\UseCache;
use App\MultiSociete\UserContext;
use App\Repository\BoUserNotificationRepository;
use App\Repository\SocieteUserNotificationRepository;
use App\Security\Voter\SameUserVoter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Exception\BadRequestException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/api/user-notifications")
 */
class BoUserNotificationController extends AbstractController
{
    private UserContext $userContext;

    public function __construct(UserContext $userContext)
    {
        $this->userContext = $userContext;
    }

    /**
     *
     * @UseCache()
     * @Cache(maxage="300")
     *
     * @Route("", methods={"GET"}, name="bo_api_check_existance_user_notifications")
     *
     * @IsGranted("ROLE_BO_USER")
     */
    public function checkExistanceUserNotifications(
        BoUserNotificationRepository $boUserNotificationRepository
    ): JsonResponse {
        if ($this->isGranted('ROLE_BO_USER')){
            return new JsonResponse([
                'hasNotifs' => $boUserNotificationRepository->checkExistanceNotifsByUser($this->userContext->getUser()),
            ]);
        } else {
            return new JsonResponse(null, JsonResponse::HTTP_NO_CONTENT);
        }
    }

    /**
     * Marque toutes les notifications d'un user lues.
     * L'id correspond au SocieteUser pour lequel récupérer les notifications
     * (doit correspondre à un SocieteUser lié à l'user acutellement connecté)
     *
     * @Route(
     *      "/{id}",
     *      methods={"POST"},
     *      name="bo_api_user_notifications_acknowledge"
     * )
     */
    public function acknowledge(
        SocieteUser $societeUser,
        Request $request,
        SocieteUserNotificationRepository $societeUserNotificationRepository
    ): JsonResponse {
        $this->denyAccessUnlessGranted(SameUserVoter::NAME, $societeUser);

        $content = $request->toArray();

        if (!isset($content['acknowledgeIds']) || !is_array($content['acknowledgeIds'])) {
            throw new BadRequestException('Excepted parameters like {"acknowledgeIds": int[]}');
        }

        $societeUserNotificationRepository->acknowledgeAllFor(
            $societeUser,
            $content['acknowledgeIds']
        );

        return new JsonResponse(null, Response::HTTP_NO_CONTENT);
    }
}

src/Controller/BO/API/DashboardController.php
<?php

namespace App\Controller\BO\API;

use App\Repository\UserRepository;
use App\Repository\ProjetRepository;
use App\Repository\SocieteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api")
 */
class DashboardController extends AbstractController
{
    private ProjetRepository $projetRepository;
    private UserRepository $userRepository;
    private SocieteRepository $societeRepository;

    public function __construct(ProjetRepository $projetRepository,UserRepository $userRepository, SocieteRepository $societeRepository)
    {
        $this->userRepository = $userRepository;
        $this->projetRepository = $projetRepository;
        $this->societeRepository = $societeRepository;
    }

    /**
     * @Route(
     *      "/historique-user",
     *      methods={"GET"},
     *      name="bo_api_historique_user"
     * )
     */
    public function historiqueUser()
    {
        for($year = 2020; $year <= (new \DateTime())->format('Y'); $year++){
            $data[$year] = []; 
            $usersByMonth = $this->userRepository->findCreatedAt($year);

            for($month = 1; $month <= 12; $month++){
                $key = array_search($month, array_column($usersByMonth, 'mois'));

                $data[$year][$month] = $key === false ? 0 : $usersByMonth[$key]['total'];
            }
        }

        return new JsonResponse([
            'data' => $data,
            'axes' => $this->generateChartAxes($data),
        ]);
    }

    /**
     * @Route(
     *      "/historique-societe",
     *      methods={"GET"},
     *      name="bo_api_historique_societe"
     * )
     */
    public function historiqueSociete()
    {
        for($year = 2020; $year <= (new \DateTime())->format('Y'); $year++){
            $data[$year] = []; 
            $societesByMonth = $this->societeRepository->findCreatedAt($year);

            for($month = 1; $month <= 12; $month++){
                $key = array_search($month, array_column($societesByMonth, 'mois'));

                $data[$year][$month] = $key === false ? 0 : $societesByMonth[$key]['total'];
            }
        }

        return new JsonResponse([
            'data' => $data,
            'axes' => $this->generateChartAxes($data),
        ]);
    }

    /**
     * @Route(
     *      "/historique-projet",
     *      methods={"GET"},
     *      name="bo_api_historique_projet"
     * )
     */
    public function historiqueProjet()
    {
        for($year = 2020; $year <= (new \DateTime())->format('Y'); $year++){
            $data[$year] = []; 
            $projetsByMonth = $this->projetRepository->findCreatedAt($year);

            for($month = 1; $month <= 12; $month++){
                $key = array_search($month, array_column($projetsByMonth, 'mois'));

                $data[$year][$month] = $key === false ? 0 : $projetsByMonth[$key]['total'];
            }
        }
        
        return new JsonResponse([
            'data' => $data,
            'axes' => $this->generateChartAxes($data),
        ]);
    }

    private function generateChartAxes(array $data)
    {
        $axes = [
            'x' => [],
            'y' => []
        ];

        foreach($data as $year => $months){
            foreach($months as $month => $value){
                $axes['x'][] = $month . '-' . $year;
                $axes['y'][] = $value;
            }
        }

        return $axes;
    }
}

src/Controller/BO/HomeController.php
<?php

namespace App\Controller\BO;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("", name="corp_app_bo_home")
     */
    public function home()
    {
        return $this->redirectToRoute('corp_app_bo_dashboard');
    }
}

templates/bo/societes/_form-add-admin.html.twig
<span>Ajouter un autre administrateur</span>

{{ form_start(formUserEmail) }}
{{ form_errors(formUserEmail) }}

<div class="row mb-4 mt-2">
    <div class="col-lg-12">
        {{ form_widget(formUserEmail.invitationEmail, {
            'attr': {
                'placeholder': 'Email de l\'administrateur'
            }
        }) }}
    </div>
    <div class="col-lg-8">
        {{ form_widget(formUserEmail.societeUserPeriods) }}
    </div>
    <div class="col-lg-4 d-flex flex-column justify-content-center align-items-center">
        <button type="submit" class="btn btn-success">
            <i class="fa fa-user-plus" aria-hidden="true"></i>
            Inviter
            <span class="d-none d-sm-inline">un autre administrateur</span>
        </button>
    </div>
</div>

{{ form_end(formUserEmail) }}

templates/bo/societes/_form-onboarding-notification-every.html.twig
<div class="row mt-4 mb-4">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                {{ form_start(formOnboardingNotificationEvery) }}
                {{ form_errors(formOnboardingNotificationEvery) }}

                {{ form_row(formOnboardingNotificationEvery.onboardingNotificationEvery) }}

                <button class="btn btn-primary" type="submit">Mettre à jour</button>

                {{ form_end(formOnboardingNotificationEvery) }}
            </div>
        </div>
    </div>
</div>

templates/bo/societes/generate-license.html.twig
{% extends 'bo/base.html.twig' %}

{% block body %}

<h1>Générer une licence pour {{ societe.raisonSociale }}</h1>

<a class="d-block mb-4" href="{{ path('corp_app_bo_societes') }}">
    <i class="fa fa-chevron-left" aria-hidden="true"></i>
    Retourner à la liste des sociétés
</a>

    <h3 class="text-center">{{ license.name }}</h3>

{{ form_start(form) }}
{{ form_errors(form) }}
{{ form_rest(form) }}

<button type="submit" class="btn btn-success">Générer la licence</button>

{{ form_end(form) }}

{% endblock %}

templates/bo/societes/new.html.twig
{% extends 'bo/base.html.twig' %}

{% block body %}

<h1>Créer une nouvelle société</h1>

<a class="d-block mb-4" href="{{ path('corp_app_bo_societes') }}">
    <i class="fa fa-chevron-left" aria-hidden="true"></i>
    Annuler et retourner à la liste des sociétés
</a>

{{ form_start(form) }}
{{ form_widget(form) }}

<button type="submit" class="btn btn-success">Initialiser la société</button>

{{ form_end(form) }}

{% endblock %}

templates/bo/societes/societe.html.twig
{% extends 'bo/base.html.twig' %}

{% block body %}

    <h1>Société {{ societe.raisonSociale }}</h1>

    <ul>
        <li>Créée le <strong>{{ societe.createdAt|format_datetime }}</strong></li>
        {% if societe.createdFrom %}
            <li>Créée depuis : <strong>{{ societe.createdFrom|trans }}</strong></li>
        {% endif %}
        {% if societe.createdBy %}
            <li>Créée par <strong>{{ societe.createdBy.fullname }}</strong></li>
        {% endif %}
    </ul>

    <a class="d-block mb-4" href="{{ path('corp_app_bo_societes') }}">
        <i class="fa fa-chevron-left" aria-hidden="true"></i>
        Retourner à la liste des sociétés
    </a>

    <h3>Administrateurs</h3>

    <table class="table datatable mb-3 hover" data-info="false" data-paging="false">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Email / Tel</th>
            <th>Statut</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for admin in societe.admins %}
            <tr>
                <td>{{ admin.user.fullname }}</td>
                <td>
                    {% if admin.user.email %}
                        {{ admin.user.email }} <br>
                    {% endif %}
                    {{ admin.user.telephone|phone_number_rdi }}
                </td>
                <td>
                    {% if admin.invitationToken %}
                        En attente de finalisation d'inscription
                        <small class="d-block">
                            Url d'invitation :
                            <strong class="d-block"><code>{{ url('corp_app_fo_user_finalize_inscription', {'token': admin.invitationToken}) }}</code></strong>
                        </small>
                    {% else %}
                        Actif
                    {% endif %}
                </td>
                <td>
                    {% if admin.invitationToken %}
                        <form
                                method="post" class="mb-2"
                                action="{{ path('corp_app_bo_societe_invite_delete', {'societeId': societe.id, 'societeUserId': admin.id}) }}"
                                onsubmit="return confirm('Supprimer cette invitation ?');"
                        >
                            <button type="submit" class="btn btn-sm btn-warning">Supprimer l'invitation</button>
                            <input type="hidden" name="token" value="{{ csrf_token('delete-invitation-admin') }}"/>
                        </form>
                        <form
                                method="post"
                                action="{{ path('corp_app_bo_societe_invite', {'societeId': societe.id, 'societeUserId': admin.id}) }}"
                                onsubmit="return confirm('Envoyer un email d\'invitation à cet administrateur ?');"
                        >
                            <button type="submit" class="btn btn-sm btn-info">Envoyer un email d'invitation</button>
                            <input type="hidden" name="token" value="{{ csrf_token('send-invitation-admin') }}"/>
                        </form>

                        <small>
                            {% if admin.invitationSentAt %}
                                <i>Dernière invitation envoyée le <b>{{ admin.invitationSentAt|format_datetime }}</b>.</i>
                            {% else %}
                                <i class="text-danger"><b>Invitation pas encore envoyée !!</b></i>
                            {% endif %}
                        </small>
                    {% endif %}
                </td>
                <td class="d-flex justify-content-end">
                    {% if not admin.invitationToken and is_granted('ROLE_ALLOWED_TO_SWITCH') %}
                        <a href="{{ path('app_home', {'_switch_user': admin.user.email }) }}" class="btn-rdi-icon">
                            <i class="fa fa-sign-in" aria-hidden="true"></i>
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% include 'bo/societes/_form-add-admin.html.twig' %}

    <h3>Licences</h3>

    {% include 'corp_app/licenses/_societe-quotas.html.twig' %}

    {% include 'corp_app/licenses/_licenses-table.html.twig' with {
        'entity': societe,
        'downloadRoute': 'corp_app_bo_license_download',
    } %}

    {% include 'bo/societes/_form-choose-product.html.twig' %}

    <h3>Notifications d'onboarding</h3>

    {% include 'bo/societes/_form-onboarding-notification-every.html.twig' %}

{% endblock %}

templates/bo/societes/societes.html.twig
{% extends 'bo/base.html.twig' %}

{% block body %}

    <h1>Sociétés</h1>

    <ul class="nav nav-tabs mb-3 tab-filter-societes">
        <li class="nav-item">
            <a class="nav-link enabled-societes active" href="#0">{{ "enabled"|trans }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled-societes" href="#0">{{ "disabled"|trans }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link all-societes" href="#0">{{ 'allString'|trans }}</a>
        </li>
        <input type="hidden" id="filter-societes-statut">
    </ul>

    <table id="societes_list_dt" class="table datatable custom-datatable hover">
        <thead>
        <tr>
            <th>Logo</th>
            <th>Société</th>
            <th>Administrateurs</th>
            <th>Utilisateurs</th>
            <th>Projets</th>
            <th>Statut</th>
            <th>Date de création</th>
            <th>Licence</th>
        </tr>
        </thead>
        <tbody>
        {% for societe in societes %}
            <tr>
                <td>{% include 'utils/_avatar.html.twig' with {societe: societe, size: 35, border: true, toExpend: true} %}</td>
                <td><a href="{{ path('corp_app_bo_societe', {'id': societe.id}) }}">{{ societe.raisonSociale }}</a></td>
                <td>{{ societe.admins|map(societeUser => "#{societeUser.user.fullnameOrEmail}")|join(', ') }}</td>
                <td>{{ societe.societeUsers|length }}</td>
                <td>{{ societe.projets|length }}</td>
                <td>{{ societe.enabled ? 'Actif' : 'Désactivé' ~ (societe.onStandBy ? ' / En veille' : '') }}</td>
                <td>{{ societe.createdAt|format_datetime }}</td>
                <td>
                    <ul>
                        <li>{{ societe.productKey|trans }}</li>
                        {% if hasTryLicense(societe) %}
                            <li>{{ "try_offer"|trans }}</li>
                        {% endif %}
                        {% if not hasActiveLicense(societe) or hasQuotaOverflow(societe) %}
                            <li>
                            <span class="text-warning"
                                  title="Cette société n'a pas de licence active, ou les quotas sont dépassés.">
                                <i class="fa fa-warning" aria-hidden="true"></i> Licence
                            </span>
                            </li>
                        {% endif %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('corp_app_bo_societes_creer') }}" class="btn btn-outline-primary">
        <i class="fa fa-plus" aria-hidden="true"></i>
        Créer une nouvelle société
    </a>

{% endblock %}